services:
  react-admin:
    build: ./react-admin
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - VITE_API_URL_BASE=http://localhost:3000
      - VITE_ADMIN_TOKEN=PINSAAR
  api:
    build: ./api
    depends_on:
      - redis
      - mongo
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MONGO_URI=mongodb://mongo:27017/droplater
      - PORT=3000
      - ADMIN_TOKEN=PINSAAR
      - HOST=0.0.0.0
      
  sink:
    build: ./sink
    depends_on:
      - redis
    ports:
      - "4000:4000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PORT=4000
     
  worker:
    build: ./worker
    depends_on:
      - redis
      - mongo
      - sink
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MONGO_URI=mongodb://mongo:27017/droplater
      - HOST=redis
      - PORT=6379
      - POLL_INTERVAL=5000

  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: droplater
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
