version: "3.8"

services:
  sink:
    build: ./sink
    env_file: ./sink/.env
    depends_on:
      - redis
    ports:
      - "4000:4000"
    environment:
      - REDIS_URL=redis://redis:6379/0
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: droplater
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
